---
swagger: "2.0"
info:
  description: "Lyric generation capstone project."
  version: "1.0.0"
  title: "Lyrics Generation"
  termsOfService: "http://swagger.io/terms/"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "34.228.251.186:8000"
schemes:
- "https"
- "http"
paths:
  /lyrics:
    post:
      tags:
      - "lyrics"
      summary: "Request lyric generation."
      description: "Request lyric generation."
      operationId: "generate_lyrics"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "LyricsRequest object that defines parameters of the lyrics desired."
        required: true
        schema:
          $ref: "#/definitions/LyricsRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "string"
        400:
          description: "Bad request"
        405:
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.lyrics_controller"
definitions:
  LyricsRequest:
    type: "object"
    properties:
      mode:
        type: "integer"
        format: "int32"
        description: "Song mode. 0 if minor, 1 if major."
      key:
        type: "integer"
      time_signature:
        type: "integer"
      danceability:
        type: "number"
      energy:
        type: "number"
      duration_ms:
        type: "number"
        minimum: 0
      loudness:
        type: "number"
      tempo:
        type: "number"
        minimum: 0
      title:
        type: "string"
        description: "Song title."
      genres:
        type: "array"
        description: "comma-separated list of genres"
        items:
          type: "string"
      beam_width:
        type: "integer"
        description: "Advanced parameter for the beam width of the beam search algorithm\
          \ used for lyrics generation."
      top_k:
        type: "integer"
        description: "Advanced parameter for the search algorithm used for lyrics\
          \ generation, indicating how many of the top sequences we keep in memory\
          \ for each word added."
      context_length:
        type: "integer"
        description: "Length of the context we keep for lyrics generation"
      max_len:
        type: "integer"
        description: "Max length in words for the lyric to be generated."
      context:
        type: "string"
        description: "Advanced parameter for language model context."
    example:
      mode: 0
      duration_ms: 0.59621339166831821554382031536079011857509613037109375
      year: 1465
      tempo: 0.5637376656633328320111786524648778140544891357421875
      title: "title"
      danceability: 0.602745618307040320615897144307382404804229736328125
      energy: 0.146581298050294517310021547018550336360931396484375
      genres:
      - "folk"
      - "gipsy"
      tags:
      - "tags"
      - "tags"
