---
swagger: "2.0"
info:
  description: "Lyric generation capstone project."
  version: "1.0.0"
  title: "Lyrics Generation"
  termsOfService: "http://swagger.io/terms/"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8080"
schemes:
- "https"
- "http"
paths:
  /lyrics:
    post:
      tags:
      - "lyrics"
      summary: "Request lyric generation."
      description: "Request lyric generation."
      operationId: "generate_lyrics"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "LyricsRequest object that defines parameters of the lyrics desired."
        required: true
        schema:
          $ref: "#/definitions/LyricsRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "string"
        400:
          description: "Bad request"
        405:
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.lyrics_controller"
definitions:
  LyricsRequest:
    type: "object"
    properties:
      mode:
        type: "integer"
        format: "int32"
        description: "Song mode. 0 if minor, 1 if major."
        minimum: 0
        maximum: 1
      danceability:
        type: "number"
        minimum: 0
        maximum: 1
      energy:
        type: "number"
        minimum: 0
        maximum: 1
      duration:
        type: "number"
        minimum: 0
      tempo:
        type: "number"
        minimum: 0
      title:
        type: "string"
        description: "Song title."
      artist:
        type: "string"
        description: "Name of the artist."
      year:
        type: "integer"
        format: "int32"
        description: "Year in which song was composed"
        minimum: 1300
        maximum: 2019
      tags:
        type: "array"
        description: "Tags to be used as seed words for lyric generation."
        items:
          type: "string"
    example:
      mode: 0
      duration: 0.59621339166831821554382031536079011857509613037109375
      artist: "artist"
      year: 1465
      tempo: 0.5637376656633328320111786524648778140544891357421875
      title: "title"
      danceability: 0.602745618307040320615897144307382404804229736328125
      energy: 0.146581298050294517310021547018550336360931396484375
      tags:
      - "tags"
      - "tags"
