/**
 * Lyrics Generation
 * Lyric generation capstone project.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LyricsGeneration);
  }
}(this, function(expect, LyricsGeneration) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LyricsGeneration.LyricsRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LyricsRequest', function() {
    it('should create an instance of LyricsRequest', function() {
      // uncomment below and update the code to test LyricsRequest
      //var instane = new LyricsGeneration.LyricsRequest();
      //expect(instance).to.be.a(LyricsGeneration.LyricsRequest);
    });

    it('should have the property mode (base name: "mode")', function() {
      // uncomment below and update the code to test the property mode
      //var instane = new LyricsGeneration.LyricsRequest();
      //expect(instance).to.be();
    });

    it('should have the property danceability (base name: "danceability")', function() {
      // uncomment below and update the code to test the property danceability
      //var instane = new LyricsGeneration.LyricsRequest();
      //expect(instance).to.be();
    });

    it('should have the property energy (base name: "energy")', function() {
      // uncomment below and update the code to test the property energy
      //var instane = new LyricsGeneration.LyricsRequest();
      //expect(instance).to.be();
    });

    it('should have the property durationMs (base name: "duration_ms")', function() {
      // uncomment below and update the code to test the property durationMs
      //var instane = new LyricsGeneration.LyricsRequest();
      //expect(instance).to.be();
    });

    it('should have the property tempo (base name: "tempo")', function() {
      // uncomment below and update the code to test the property tempo
      //var instane = new LyricsGeneration.LyricsRequest();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instane = new LyricsGeneration.LyricsRequest();
      //expect(instance).to.be();
    });

    it('should have the property genres (base name: "genres")', function() {
      // uncomment below and update the code to test the property genres
      //var instane = new LyricsGeneration.LyricsRequest();
      //expect(instance).to.be();
    });

  });

}));
